name: Build and Publish NuGet Package

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')
          echo "Extracted version: $TAG"
          echo "version=$TAG" >> $GITHUB_ENV

      - name: Copy README.md to project folder
        run: |
          cp ../README.md ./NetEnvExtensions/

      - name: Restore dependencies
        run: dotnet restore NetEnvExtensions/NetEnvExtensions.csproj

      - name: Build
        run: dotnet build NetEnvExtensions/NetEnvExtensions.csproj --configuration Release --no-restore

      - name: Build and Pack
        run: dotnet pack NetEnvExtensions/NetEnvExtensions.csproj --configuration Release --output ./nupkgs /p:Version=${{ env.version }}

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source nuget.org
